### DISCUSSION TITLE
How to handle duplicate column names?

### DISCUSSION THREAD

**Discussion by evbo** [BurntSushi/rust-csv#368] [Q&A]
So another disgusting csv format someone handed me:

```shell
animal,max_height,average,max_weight,average
zebra,62,53,460,350,
```

The thinking was, why distinguish `average` when we can assume it is the average of the column that comes before it?

But this leads to errors such as: 
> duplicate field `average`

Is the cleanest way to handle this so some string replacement on the raw headers and then performing `set_headers` with the augmented versions?

**Comment by BurntSushi** [comment]
I think you should just be able to do set_headers without any sort of string replacement.

**Reply by evbo** [reply]
the problem is during deserialization though, because `average` cannot map to multiple struct fields, can it?

But if I uniquify the column names it works, I just thought to ask in case there was a built-in way to handle this.

**Reply by BurntSushi** [reply]
Did you try what I suggested? If not, why not? And if you did, what happened? It helps to share code. It tells me _exactly_ what you're trying. Because it may be the case that something is going wrong that is incidental to the actual question you're asking.

Here's an example:

```rust
#[allow(dead_code)]
#[derive(Debug, serde::Deserialize)]
struct Row {
    animal: String,
    max_height: i64,
    average_height: i64,
    max_weight: i64,
    average_weight: i64,
}

fn main() -> anyhow::Result<()> {
    let data = "\
animal,max_height,average,max_weight,average
zebra,62,53,460,350
";

    let mut rdr = csv::Reader::from_reader(data.as_bytes());
    rdr.set_headers(csv::StringRecord::from(vec![
        "animal",
        "max_height",
        "average_height",
        "max_weight",
        "average_weight",
    ]));
    for result in rdr.deserialize().skip(1) {
        let row: Row = result?;
        println!("{row:?}");
    }
    Ok(())
}
```

with this `Cargo.toml`:

```toml
[package]
publish = false
name = "csv-duplicate-headers"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
csv = "1.3.0"
serde = { version = "1.0.203", features = ["derive"] }

[[bin]]
name = "csv-duplicate-headers"
path = "main.rs"

[profile.release]
debug = true
```

And its output is:

```
$ cargo r -q
Row { animal: "zebra", max_height: 62, average_height: 53, max_weight: 460, average_weight: 350 }
```
