### ISSUE TITLE
Make serde an optional dependency

### ISSUE THREAD

**Issue by gabo01** [BurntSushi/rust-csv#126]
From the example I have the impression that serde is not actually needed in order to use this crate. If I am correct, then it would be better to specify serde as an optional dependency and compile it only if the user wants it. It would be like this:

`Cargo.toml`
```toml
[dependencies]
serde = {version = "1.0.55", optional = true}

[features]
default = ["serde"]
```

This way, if the user does not want serde, all what it has to do is to put this in his `Cargo.toml`

```toml
[dependencies.csv]
version = "1"
default-features = false
```
