### ISSUE TITLE
Bad cargo configuration in README.md

### ISSUE THREAD

**Issue by TeXitoi** [BurntSushi/rust-csv#9]
README.md says to add to Cargo.toml:

``` toml
[dependencies.rust-csv]
git = "git://github.com/BurntSushi/rust-csv"
```

but it should be

``` toml
[dependencies.csv]
git = "git://github.com/BurntSushi/rust-csv"
```

i.e. the dependency is `csv` and not `rust-csv`.
